apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: registry.kluster.ptych.net/frontend # to reproduce later change with your registry and log to it with docker login
deploy:
  kubectl:
    manifests:
      - k8s-deploy-dev/*.yaml